/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LibAsset {
  export type AssetStruct = {
    assetType: BigNumberish;
    contractAddress: AddressLike;
    assetId: BigNumberish;
    assetAmount: BigNumberish;
  };

  export type AssetStructOutput = [
    assetType: bigint,
    contractAddress: string,
    assetId: bigint,
    assetAmount: bigint
  ] & {
    assetType: bigint;
    contractAddress: string;
    assetId: bigint;
    assetAmount: bigint;
  };
}

export declare namespace LibOrder {
  export type OrderItemStruct = {
    makeAsset: LibAsset.AssetStruct;
    takeAsset: LibAsset.AssetStruct;
    start: BigNumberish;
    end: BigNumberish;
  };

  export type OrderItemStructOutput = [
    makeAsset: LibAsset.AssetStructOutput,
    takeAsset: LibAsset.AssetStructOutput,
    start: bigint,
    end: bigint
  ] & {
    makeAsset: LibAsset.AssetStructOutput;
    takeAsset: LibAsset.AssetStructOutput;
    start: bigint;
    end: bigint;
  };

  export type OrderStruct = {
    orderType: BigNumberish;
    items: LibOrder.OrderItemStruct[];
    maker: AddressLike;
    taker: AddressLike;
    root: BytesLike;
    salt: BigNumberish;
    signature: BytesLike;
  };

  export type OrderStructOutput = [
    orderType: bigint,
    items: LibOrder.OrderItemStructOutput[],
    maker: string,
    taker: string,
    root: string,
    salt: bigint,
    signature: string
  ] & {
    orderType: bigint;
    items: LibOrder.OrderItemStructOutput[];
    maker: string;
    taker: string;
    root: string;
    salt: bigint;
    signature: string;
  };
}

export interface MarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE_BPS"
      | "acceptBid"
      | "assetTransferAgent"
      | "batchMatchOrders"
      | "cancelOrder"
      | "eip712Domain"
      | "feeBps"
      | "feeRecipient"
      | "isOrderCancelled"
      | "isOrderFullyFilled"
      | "matchOrders"
      | "orderFillAmount"
      | "owner"
      | "renounceOwnership"
      | "setAssetTransferAgent"
      | "setFeeBps"
      | "setFeeRecipient"
      | "transferOwnership"
      | "verifyMerkleProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CancelOrder"
      | "EIP712DomainChanged"
      | "OrderMatched"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [LibOrder.OrderStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetTransferAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchMatchOrders",
    values: [
      LibOrder.OrderStruct[],
      LibOrder.OrderStruct,
      BigNumberish[],
      BytesLike[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [LibOrder.OrderStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOrderCancelled",
    values: [LibOrder.OrderStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isOrderFullyFilled",
    values: [LibOrder.OrderStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchOrders",
    values: [
      LibOrder.OrderStruct,
      LibOrder.OrderStruct,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "orderFillAmount",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetTransferAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMerkleProof",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetTransferAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchMatchOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOrderCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOrderFullyFilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderFillAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetTransferAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMerkleProof",
    data: BytesLike
  ): Result;
}

export namespace CancelOrderEvent {
  export type InputTuple = [orderHash: BytesLike];
  export type OutputTuple = [orderHash: string];
  export interface OutputObject {
    orderHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderMatchedEvent {
  export type InputTuple = [
    orderHash: BytesLike,
    maker: AddressLike,
    taker: AddressLike,
    fillAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderHash: string,
    maker: string,
    taker: string,
    fillAmount: bigint
  ];
  export interface OutputObject {
    orderHash: string;
    maker: string;
    taker: string;
    fillAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Marketplace extends BaseContract {
  connect(runner?: ContractRunner | null): Marketplace;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptBid: TypedContractMethod<
    [
      bidOrder: LibOrder.OrderStruct,
      orderItemIndex: BigNumberish,
      sellAmount: BigNumberish
    ],
    [void],
    "payable"
  >;

  assetTransferAgent: TypedContractMethod<[], [string], "view">;

  batchMatchOrders: TypedContractMethod<
    [
      makerOrders: LibOrder.OrderStruct[],
      takerOrder: LibOrder.OrderStruct,
      orderItemIndices: BigNumberish[],
      proofs: BytesLike[][]
    ],
    [void],
    "payable"
  >;

  cancelOrder: TypedContractMethod<
    [order: LibOrder.OrderStruct, orderItemIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  isOrderCancelled: TypedContractMethod<
    [order: LibOrder.OrderStruct, orderItemIndex: BigNumberish],
    [boolean],
    "view"
  >;

  isOrderFullyFilled: TypedContractMethod<
    [order: LibOrder.OrderStruct, orderItemIndex: BigNumberish],
    [boolean],
    "view"
  >;

  matchOrders: TypedContractMethod<
    [
      makerOrder: LibOrder.OrderStruct,
      takerOrder: LibOrder.OrderStruct,
      orderItemIndex: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "payable"
  >;

  orderFillAmount: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAssetTransferAgent: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeBps: TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [_feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyMerkleProof: TypedContractMethod<
    [proof: BytesLike[], root: BytesLike, leaf: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [
      bidOrder: LibOrder.OrderStruct,
      orderItemIndex: BigNumberish,
      sellAmount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "assetTransferAgent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchMatchOrders"
  ): TypedContractMethod<
    [
      makerOrders: LibOrder.OrderStruct[],
      takerOrder: LibOrder.OrderStruct,
      orderItemIndices: BigNumberish[],
      proofs: BytesLike[][]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<
    [order: LibOrder.OrderStruct, orderItemIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isOrderCancelled"
  ): TypedContractMethod<
    [order: LibOrder.OrderStruct, orderItemIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOrderFullyFilled"
  ): TypedContractMethod<
    [order: LibOrder.OrderStruct, orderItemIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchOrders"
  ): TypedContractMethod<
    [
      makerOrder: LibOrder.OrderStruct,
      takerOrder: LibOrder.OrderStruct,
      orderItemIndex: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "orderFillAmount"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAssetTransferAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeBps"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_feeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyMerkleProof"
  ): TypedContractMethod<
    [proof: BytesLike[], root: BytesLike, leaf: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "CancelOrder"
  ): TypedContractEvent<
    CancelOrderEvent.InputTuple,
    CancelOrderEvent.OutputTuple,
    CancelOrderEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "OrderMatched"
  ): TypedContractEvent<
    OrderMatchedEvent.InputTuple,
    OrderMatchedEvent.OutputTuple,
    OrderMatchedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CancelOrder(bytes32)": TypedContractEvent<
      CancelOrderEvent.InputTuple,
      CancelOrderEvent.OutputTuple,
      CancelOrderEvent.OutputObject
    >;
    CancelOrder: TypedContractEvent<
      CancelOrderEvent.InputTuple,
      CancelOrderEvent.OutputTuple,
      CancelOrderEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "OrderMatched(bytes32,address,address,uint256)": TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;
    OrderMatched: TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
