/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAssetTransferAgent } from "./IAssetTransferAgent";
export type { INodeAdmin } from "./INodeAdmin";
export type { INodesStorage } from "./INodesStorage";
export type { IUsageDepositor } from "./IUsageDepositor";
export type { IVault } from "./IVault";
