/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface NodesStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addNodes"
      | "getTotalValidNodes"
      | "getValidNodes"
      | "isValidNode"
      | "owner"
      | "removeNode"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NodeAdded" | "NodeRemoved" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addNodes",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalValidNodes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidNodes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addNodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalValidNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace NodeAddedEvent {
  export type InputTuple = [node: AddressLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeRemovedEvent {
  export type InputTuple = [node: AddressLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodesStorage extends BaseContract {
  connect(runner?: ContractRunner | null): NodesStorage;
  waitForDeployment(): Promise<this>;

  interface: NodesStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addNodes: TypedContractMethod<
    [newNodes: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getTotalValidNodes: TypedContractMethod<[], [bigint], "view">;

  getValidNodes: TypedContractMethod<[], [string[]], "view">;

  isValidNode: TypedContractMethod<[node: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeNode: TypedContractMethod<[node: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addNodes"
  ): TypedContractMethod<[newNodes: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTotalValidNodes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidNodes"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isValidNode"
  ): TypedContractMethod<[node: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeNode"
  ): TypedContractMethod<[node: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NodeAdded"
  ): TypedContractEvent<
    NodeAddedEvent.InputTuple,
    NodeAddedEvent.OutputTuple,
    NodeAddedEvent.OutputObject
  >;
  getEvent(
    key: "NodeRemoved"
  ): TypedContractEvent<
    NodeRemovedEvent.InputTuple,
    NodeRemovedEvent.OutputTuple,
    NodeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "NodeAdded(address)": TypedContractEvent<
      NodeAddedEvent.InputTuple,
      NodeAddedEvent.OutputTuple,
      NodeAddedEvent.OutputObject
    >;
    NodeAdded: TypedContractEvent<
      NodeAddedEvent.InputTuple,
      NodeAddedEvent.OutputTuple,
      NodeAddedEvent.OutputObject
    >;

    "NodeRemoved(address)": TypedContractEvent<
      NodeRemovedEvent.InputTuple,
      NodeRemovedEvent.OutputTuple,
      NodeRemovedEvent.OutputObject
    >;
    NodeRemoved: TypedContractEvent<
      NodeRemovedEvent.InputTuple,
      NodeRemovedEvent.OutputTuple,
      NodeRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
