/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuctionVault,
  IAuctionVaultInterface,
} from "../../../contracts/interfaces/IAuctionVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "auctionHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "bidder",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "auctionHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        internalType: "address",
        name: "bidder",
        type: "address",
      },
    ],
    name: "finalize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "auctionHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "bidder",
        type: "address",
      },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuctionVault__factory {
  static readonly abi = _abi;
  static createInterface(): IAuctionVaultInterface {
    return new Interface(_abi) as IAuctionVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAuctionVault {
    return new Contract(address, _abi, runner) as unknown as IAuctionVault;
  }
}
