/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INodeAdmin,
  INodeAdminInterface,
} from "../../../contracts/interfaces/INodeAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "node",
        type: "address",
      },
    ],
    name: "remove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INodeAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): INodeAdminInterface {
    return new Interface(_abi) as INodeAdminInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INodeAdmin {
    return new Contract(address, _abi, runner) as unknown as INodeAdmin;
  }
}
